// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ODataErrors;
using OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.Calendars.Item.Events.Item.Calendar
{
    /// <summary>
    /// Provides operations to manage the calendar property of the microsoft.graph.event entity.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public partial class CalendarRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.Calendars.Item.Events.Item.Calendar.CalendarRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CalendarRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/me/calendars/{calendar%2Did}/events/{event%2Did}/calendar{?%24expand,%24select}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.Calendars.Item.Events.Item.Calendar.CalendarRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CalendarRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/me/calendars/{calendar%2Did}/events/{event%2Did}/calendar{?%24expand,%24select}", rawUrl)
        {
        }
        /// <summary>
        /// The calendar that contains the event. Navigation property. Read-only.
        /// </summary>
        /// <returns>A <see cref="global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Calendar"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ODataErrors.ODataError">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Calendar?> GetAsync(Action<RequestConfiguration<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.Calendars.Item.Events.Item.Calendar.CalendarRequestBuilder.CalendarRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Calendar> GetAsync(Action<RequestConfiguration<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.Calendars.Item.Events.Item.Calendar.CalendarRequestBuilder.CalendarRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ODataErrors.ODataError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Calendar>(requestInfo, global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Calendar.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// The calendar that contains the event. Navigation property. Read-only.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.Calendars.Item.Events.Item.Calendar.CalendarRequestBuilder.CalendarRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.Calendars.Item.Events.Item.Calendar.CalendarRequestBuilder.CalendarRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.Calendars.Item.Events.Item.Calendar.CalendarRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.Calendars.Item.Events.Item.Calendar.CalendarRequestBuilder WithUrl(string rawUrl)
        {
            return new global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.Calendars.Item.Events.Item.Calendar.CalendarRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// The calendar that contains the event. Navigation property. Read-only.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
        public partial class CalendarRequestBuilderGetQueryParameters 
        {
            /// <summary>Expand related entities</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24expand")]
            public string[]? Expand { get; set; }
#nullable restore
#else
            [QueryParameter("%24expand")]
            public string[] Expand { get; set; }
#endif
            /// <summary>Select properties to be returned</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("%24select")]
            public string[]? Select { get; set; }
#nullable restore
#else
            [QueryParameter("%24select")]
            public string[] Select { get; set; }
#endif
        }
    }
}
