// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    #pragma warning disable CS1591
    public enum AttendeeType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "required")]
        #pragma warning disable CS1591
        Required,
        #pragma warning restore CS1591
        [EnumMember(Value = "optional")]
        #pragma warning disable CS1591
        Optional,
        #pragma warning restore CS1591
        [EnumMember(Value = "resource")]
        #pragma warning disable CS1591
        Resource,
        #pragma warning restore CS1591
    }
}
