// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    #pragma warning disable CS1591
    public enum CalendarSharingActionType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "accept")]
        #pragma warning disable CS1591
        Accept,
        #pragma warning restore CS1591
    }
}
