// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    #pragma warning disable CS1591
    public enum EventType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "singleInstance")]
        #pragma warning disable CS1591
        SingleInstance,
        #pragma warning restore CS1591
        [EnumMember(Value = "occurrence")]
        #pragma warning disable CS1591
        Occurrence,
        #pragma warning restore CS1591
        [EnumMember(Value = "exception")]
        #pragma warning disable CS1591
        Exception,
        #pragma warning restore CS1591
        [EnumMember(Value = "seriesMaster")]
        #pragma warning disable CS1591
        SeriesMaster,
        #pragma warning restore CS1591
    }
}
