// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    #pragma warning disable CS1591
    public partial class Event : global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.OutlookItem, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>true if the meeting organizer allows invitees to propose a new time when responding; otherwise, false. Optional. The default is true.</summary>
        public bool? AllowNewTimeProposals
        {
            get { return BackingStore?.Get<bool?>("allowNewTimeProposals"); }
            set { BackingStore?.Set("allowNewTimeProposals", value); }
        }
        /// <summary>The collection of FileAttachment, ItemAttachment, and referenceAttachment attachments for the event. Navigation property. Read-only. Nullable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Attachment>? Attachments
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Attachment>?>("attachments"); }
            set { BackingStore?.Set("attachments", value); }
        }
#nullable restore
#else
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Attachment> Attachments
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Attachment>>("attachments"); }
            set { BackingStore?.Set("attachments", value); }
        }
#endif
        /// <summary>The collection of attendees for the event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Attendee>? Attendees
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Attendee>?>("attendees"); }
            set { BackingStore?.Set("attendees", value); }
        }
#nullable restore
#else
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Attendee> Attendees
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Attendee>>("attendees"); }
            set { BackingStore?.Set("attendees", value); }
        }
#endif
        /// <summary>The body of the message associated with the event. It can be in HTML or text format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ItemBody? Body
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ItemBody?>("body"); }
            set { BackingStore?.Set("body", value); }
        }
#nullable restore
#else
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ItemBody Body
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ItemBody>("body"); }
            set { BackingStore?.Set("body", value); }
        }
#endif
        /// <summary>The preview of the message associated with the event. It&apos;s in text format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BodyPreview
        {
            get { return BackingStore?.Get<string?>("bodyPreview"); }
            set { BackingStore?.Set("bodyPreview", value); }
        }
#nullable restore
#else
        public string BodyPreview
        {
            get { return BackingStore?.Get<string>("bodyPreview"); }
            set { BackingStore?.Set("bodyPreview", value); }
        }
#endif
        /// <summary>The calendar that contains the event. Navigation property. Read-only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Calendar? Calendar
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Calendar?>("calendar"); }
            set { BackingStore?.Set("calendar", value); }
        }
#nullable restore
#else
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Calendar Calendar
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Calendar>("calendar"); }
            set { BackingStore?.Set("calendar", value); }
        }
#endif
        /// <summary>Contains occurrenceId property values of canceled instances in a recurring series, if the event is the series master. Instances in a recurring series that are canceled are called canceled occurences.Requires $select to retrieve. Only returned in a Get operation that specifies the ID (seriesMasterId property value) of a series master event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CancelledOccurrences
        {
            get { return BackingStore?.Get<List<string>?>("cancelledOccurrences"); }
            set { BackingStore?.Set("cancelledOccurrences", value); }
        }
#nullable restore
#else
        public List<string> CancelledOccurrences
        {
            get { return BackingStore?.Get<List<string>>("cancelledOccurrences"); }
            set { BackingStore?.Set("cancelledOccurrences", value); }
        }
#endif
        /// <summary>The date, time, and time zone that the event ends. By default, the end time is in UTC.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone? End
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone?>("end"); }
            set { BackingStore?.Set("end", value); }
        }
#nullable restore
#else
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone End
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone>("end"); }
            set { BackingStore?.Set("end", value); }
        }
#endif
        /// <summary>Contains the id property values of the event instances that are exceptions in a recurring series.Exceptions can differ from other occurrences in a recurring series, such as the subject, start or end times, or attendees. Exceptions don&apos;t include canceled occurrences.Requires $select and $expand to retrieve. Only returned in a GET operation that specifies the ID (seriesMasterId property value) of a series master event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Event>? ExceptionOccurrences
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Event>?>("exceptionOccurrences"); }
            set { BackingStore?.Set("exceptionOccurrences", value); }
        }
#nullable restore
#else
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Event> ExceptionOccurrences
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Event>>("exceptionOccurrences"); }
            set { BackingStore?.Set("exceptionOccurrences", value); }
        }
#endif
        /// <summary>The collection of open extensions defined for the event. Nullable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Extension>? Extensions
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Extension>?>("extensions"); }
            set { BackingStore?.Set("extensions", value); }
        }
#nullable restore
#else
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Extension> Extensions
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Extension>>("extensions"); }
            set { BackingStore?.Set("extensions", value); }
        }
#endif
        /// <summary>Set to true if the event has attachments.</summary>
        public bool? HasAttachments
        {
            get { return BackingStore?.Get<bool?>("hasAttachments"); }
            set { BackingStore?.Set("hasAttachments", value); }
        }
        /// <summary>When set to true, each attendee only sees themselves in the meeting request and meeting Tracking list. The default is false.</summary>
        public bool? HideAttendees
        {
            get { return BackingStore?.Get<bool?>("hideAttendees"); }
            set { BackingStore?.Set("hideAttendees", value); }
        }
        /// <summary>A unique identifier for an event across calendars. This ID is different for each occurrence in a recurring series. Read-only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ICalUId
        {
            get { return BackingStore?.Get<string?>("iCalUId"); }
            set { BackingStore?.Set("iCalUId", value); }
        }
#nullable restore
#else
        public string ICalUId
        {
            get { return BackingStore?.Get<string>("iCalUId"); }
            set { BackingStore?.Set("iCalUId", value); }
        }
#endif
        /// <summary>The importance of the event. The possible values are: low, normal, high.</summary>
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Importance? Importance
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Importance?>("importance"); }
            set { BackingStore?.Set("importance", value); }
        }
        /// <summary>The occurrences of a recurring series, if the event is a series master. This property includes occurrences that are part of the recurrence pattern, and exceptions modified, but doesn&apos;t include occurrences canceled from the series. Navigation property. Read-only. Nullable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Event>? Instances
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Event>?>("instances"); }
            set { BackingStore?.Set("instances", value); }
        }
#nullable restore
#else
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Event> Instances
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Event>>("instances"); }
            set { BackingStore?.Set("instances", value); }
        }
#endif
        /// <summary>Set to true if the event lasts all day. If true, regardless of whether it&apos;s a single-day or multi-day event, start, and endtime must be set to midnight and be in the same time zone.</summary>
        public bool? IsAllDay
        {
            get { return BackingStore?.Get<bool?>("isAllDay"); }
            set { BackingStore?.Set("isAllDay", value); }
        }
        /// <summary>Set to true if the event has been canceled.</summary>
        public bool? IsCancelled
        {
            get { return BackingStore?.Get<bool?>("isCancelled"); }
            set { BackingStore?.Set("isCancelled", value); }
        }
        /// <summary>Set to true if the user has updated the meeting in Outlook but hasn&apos;t sent the updates to attendees. Set to false if all changes are sent, or if the event is an appointment without any attendees.</summary>
        public bool? IsDraft
        {
            get { return BackingStore?.Get<bool?>("isDraft"); }
            set { BackingStore?.Set("isDraft", value); }
        }
        /// <summary>True if this event has online meeting information (that is, onlineMeeting points to an onlineMeetingInfo resource), false otherwise. Default is false (onlineMeeting is null). Optional.  After you set isOnlineMeeting to true, Microsoft Graph initializes onlineMeeting. Subsequently, Outlook ignores any further changes to isOnlineMeeting, and the meeting remains available online.</summary>
        public bool? IsOnlineMeeting
        {
            get { return BackingStore?.Get<bool?>("isOnlineMeeting"); }
            set { BackingStore?.Set("isOnlineMeeting", value); }
        }
        /// <summary>Set to true if the calendar owner (specified by the owner property of the calendar) is the organizer of the event (specified by the organizer property of the event). It also applies if a delegate organized the event on behalf of the owner.</summary>
        public bool? IsOrganizer
        {
            get { return BackingStore?.Get<bool?>("isOrganizer"); }
            set { BackingStore?.Set("isOrganizer", value); }
        }
        /// <summary>Set to true if an alert is set to remind the user of the event.</summary>
        public bool? IsReminderOn
        {
            get { return BackingStore?.Get<bool?>("isReminderOn"); }
            set { BackingStore?.Set("isReminderOn", value); }
        }
        /// <summary>The location of the event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Location? Location
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Location?>("location"); }
            set { BackingStore?.Set("location", value); }
        }
#nullable restore
#else
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Location Location
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Location>("location"); }
            set { BackingStore?.Set("location", value); }
        }
#endif
        /// <summary>The locations where the event is held or attended from. The location and locations properties always correspond with each other. If you update the location property, any prior locations in the locations collection are removed and replaced by the new location value.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Location>? Locations
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Location>?>("locations"); }
            set { BackingStore?.Set("locations", value); }
        }
#nullable restore
#else
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Location> Locations
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Location>>("locations"); }
            set { BackingStore?.Set("locations", value); }
        }
#endif
        /// <summary>The collection of multi-value extended properties defined for the event. Read-only. Nullable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.MultiValueLegacyExtendedProperty>? MultiValueExtendedProperties
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.MultiValueLegacyExtendedProperty>?>("multiValueExtendedProperties"); }
            set { BackingStore?.Set("multiValueExtendedProperties", value); }
        }
#nullable restore
#else
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.MultiValueLegacyExtendedProperty> MultiValueExtendedProperties
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.MultiValueLegacyExtendedProperty>>("multiValueExtendedProperties"); }
            set { BackingStore?.Set("multiValueExtendedProperties", value); }
        }
#endif
        /// <summary>Details for an attendee to join the meeting online. The default is null. Read-only. After you set the isOnlineMeeting and onlineMeetingProvider properties to enable a meeting online, Microsoft Graph initializes onlineMeeting. When set, the meeting remains available online, and you can&apos;t change the isOnlineMeeting, onlineMeetingProvider, and onlneMeeting properties again.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.OnlineMeetingInfo? OnlineMeeting
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.OnlineMeetingInfo?>("onlineMeeting"); }
            set { BackingStore?.Set("onlineMeeting", value); }
        }
#nullable restore
#else
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.OnlineMeetingInfo OnlineMeeting
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.OnlineMeetingInfo>("onlineMeeting"); }
            set { BackingStore?.Set("onlineMeeting", value); }
        }
#endif
        /// <summary>Represents the online meeting service provider. By default, onlineMeetingProvider is unknown. The possible values are unknown, teamsForBusiness, skypeForBusiness, and skypeForConsumer. Optional.  After you set onlineMeetingProvider, Microsoft Graph initializes onlineMeeting. Subsequently, you can&apos;t change onlineMeetingProvider again, and the meeting remains available online.</summary>
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.OnlineMeetingProviderType? OnlineMeetingProvider
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.OnlineMeetingProviderType?>("onlineMeetingProvider"); }
            set { BackingStore?.Set("onlineMeetingProvider", value); }
        }
        /// <summary>A URL for an online meeting. The property is set only when an organizer specifies in Outlook that an event is an online meeting such as Skype. Read-only.To access the URL to join an online meeting, use joinUrl which is exposed via the onlineMeeting property of the event. The onlineMeetingUrl property will be deprecated in the future.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OnlineMeetingUrl
        {
            get { return BackingStore?.Get<string?>("onlineMeetingUrl"); }
            set { BackingStore?.Set("onlineMeetingUrl", value); }
        }
#nullable restore
#else
        public string OnlineMeetingUrl
        {
            get { return BackingStore?.Get<string>("onlineMeetingUrl"); }
            set { BackingStore?.Set("onlineMeetingUrl", value); }
        }
#endif
        /// <summary>The organizer of the event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient? Organizer
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient?>("organizer"); }
            set { BackingStore?.Set("organizer", value); }
        }
#nullable restore
#else
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient Organizer
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>("organizer"); }
            set { BackingStore?.Set("organizer", value); }
        }
#endif
        /// <summary>The end time zone that was set when the event was created. A value of tzone://Microsoft/Custom indicates that a legacy custom time zone was set in desktop Outlook.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginalEndTimeZone
        {
            get { return BackingStore?.Get<string?>("originalEndTimeZone"); }
            set { BackingStore?.Set("originalEndTimeZone", value); }
        }
#nullable restore
#else
        public string OriginalEndTimeZone
        {
            get { return BackingStore?.Get<string>("originalEndTimeZone"); }
            set { BackingStore?.Set("originalEndTimeZone", value); }
        }
#endif
        /// <summary>Represents the start time of an event when it&apos;s initially created as an occurrence or exception in a recurring series. This property is not returned for events that are single instances. Its date and time information is expressed in ISO 8601 format and is always in UTC. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z</summary>
        public DateTimeOffset? OriginalStart
        {
            get { return BackingStore?.Get<DateTimeOffset?>("originalStart"); }
            set { BackingStore?.Set("originalStart", value); }
        }
        /// <summary>The start time zone that was set when the event was created. A value of tzone://Microsoft/Custom indicates that a legacy custom time zone was set in desktop Outlook.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginalStartTimeZone
        {
            get { return BackingStore?.Get<string?>("originalStartTimeZone"); }
            set { BackingStore?.Set("originalStartTimeZone", value); }
        }
#nullable restore
#else
        public string OriginalStartTimeZone
        {
            get { return BackingStore?.Get<string>("originalStartTimeZone"); }
            set { BackingStore?.Set("originalStartTimeZone", value); }
        }
#endif
        /// <summary>The recurrence pattern for the event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.PatternedRecurrence? Recurrence
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.PatternedRecurrence?>("recurrence"); }
            set { BackingStore?.Set("recurrence", value); }
        }
#nullable restore
#else
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.PatternedRecurrence Recurrence
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.PatternedRecurrence>("recurrence"); }
            set { BackingStore?.Set("recurrence", value); }
        }
#endif
        /// <summary>The number of minutes before the event start time that the reminder alert occurs.</summary>
        public int? ReminderMinutesBeforeStart
        {
            get { return BackingStore?.Get<int?>("reminderMinutesBeforeStart"); }
            set { BackingStore?.Set("reminderMinutesBeforeStart", value); }
        }
        /// <summary>Default is true, which represents the organizer would like an invitee to send a response to the event.</summary>
        public bool? ResponseRequested
        {
            get { return BackingStore?.Get<bool?>("responseRequested"); }
            set { BackingStore?.Set("responseRequested", value); }
        }
        /// <summary>Indicates the type of response sent in response to an event message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ResponseStatus? ResponseStatus
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ResponseStatus?>("responseStatus"); }
            set { BackingStore?.Set("responseStatus", value); }
        }
#nullable restore
#else
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ResponseStatus ResponseStatus
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ResponseStatus>("responseStatus"); }
            set { BackingStore?.Set("responseStatus", value); }
        }
#endif
        /// <summary>The possible values are: normal, personal, private, and confidential.</summary>
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Sensitivity? Sensitivity
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Sensitivity?>("sensitivity"); }
            set { BackingStore?.Set("sensitivity", value); }
        }
        /// <summary>The ID for the recurring series master item, if this event is part of a recurring series.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SeriesMasterId
        {
            get { return BackingStore?.Get<string?>("seriesMasterId"); }
            set { BackingStore?.Set("seriesMasterId", value); }
        }
#nullable restore
#else
        public string SeriesMasterId
        {
            get { return BackingStore?.Get<string>("seriesMasterId"); }
            set { BackingStore?.Set("seriesMasterId", value); }
        }
#endif
        /// <summary>The status to show. The possible values are: free, tentative, busy, oof, workingElsewhere, unknown.</summary>
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.FreeBusyStatus? ShowAs
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.FreeBusyStatus?>("showAs"); }
            set { BackingStore?.Set("showAs", value); }
        }
        /// <summary>The collection of single-value extended properties defined for the event. Read-only. Nullable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.SingleValueLegacyExtendedProperty>? SingleValueExtendedProperties
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.SingleValueLegacyExtendedProperty>?>("singleValueExtendedProperties"); }
            set { BackingStore?.Set("singleValueExtendedProperties", value); }
        }
#nullable restore
#else
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.SingleValueLegacyExtendedProperty> SingleValueExtendedProperties
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.SingleValueLegacyExtendedProperty>>("singleValueExtendedProperties"); }
            set { BackingStore?.Set("singleValueExtendedProperties", value); }
        }
#endif
        /// <summary>The start date, time, and time zone of the event. By default, the start time is in UTC.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone? Start
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone?>("start"); }
            set { BackingStore?.Set("start", value); }
        }
#nullable restore
#else
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone Start
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone>("start"); }
            set { BackingStore?.Set("start", value); }
        }
#endif
        /// <summary>The text of the event&apos;s subject line.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject
        {
            get { return BackingStore?.Get<string?>("subject"); }
            set { BackingStore?.Set("subject", value); }
        }
#nullable restore
#else
        public string Subject
        {
            get { return BackingStore?.Get<string>("subject"); }
            set { BackingStore?.Set("subject", value); }
        }
#endif
        /// <summary>A custom identifier specified by a client app for the server to avoid redundant POST operations in case of client retries to create the same event. It&apos;s useful when low network connectivity causes the client to time out before receiving a response from the server for the client&apos;s prior create-event request. After you set transactionId when creating an event, you can&apos;t change transactionId in a subsequent update. This property is only returned in a response payload if an app has set it. Optional.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TransactionId
        {
            get { return BackingStore?.Get<string?>("transactionId"); }
            set { BackingStore?.Set("transactionId", value); }
        }
#nullable restore
#else
        public string TransactionId
        {
            get { return BackingStore?.Get<string>("transactionId"); }
            set { BackingStore?.Set("transactionId", value); }
        }
#endif
        /// <summary>The event type. The possible values are: singleInstance, occurrence, exception, seriesMaster. Read-only</summary>
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.EventType? Type
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.EventType?>("type"); }
            set { BackingStore?.Set("type", value); }
        }
        /// <summary>The URL to open the event in Outlook on the web.Outlook on the web opens the event in the browser if you are signed in to your mailbox. Otherwise, Outlook on the web prompts you to sign in.This URL can&apos;t be accessed from within an iFrame.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebLink
        {
            get { return BackingStore?.Get<string?>("webLink"); }
            set { BackingStore?.Set("webLink", value); }
        }
#nullable restore
#else
        public string WebLink
        {
            get { return BackingStore?.Get<string>("webLink"); }
            set { BackingStore?.Set("webLink", value); }
        }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Event"/> and sets the default values.
        /// </summary>
        public Event() : base()
        {
            OdataType = "#microsoft.graph.event";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Event"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Event CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Event();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "allowNewTimeProposals", n => { AllowNewTimeProposals = n.GetBoolValue(); } },
                { "attachments", n => { Attachments = n.GetCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Attachment>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Attachment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "attendees", n => { Attendees = n.GetCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Attendee>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Attendee.CreateFromDiscriminatorValue)?.AsList(); } },
                { "body", n => { Body = n.GetObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ItemBody>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ItemBody.CreateFromDiscriminatorValue); } },
                { "bodyPreview", n => { BodyPreview = n.GetStringValue(); } },
                { "calendar", n => { Calendar = n.GetObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Calendar>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Calendar.CreateFromDiscriminatorValue); } },
                { "cancelledOccurrences", n => { CancelledOccurrences = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "end", n => { End = n.GetObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone.CreateFromDiscriminatorValue); } },
                { "exceptionOccurrences", n => { ExceptionOccurrences = n.GetCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Event>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Event.CreateFromDiscriminatorValue)?.AsList(); } },
                { "extensions", n => { Extensions = n.GetCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Extension>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Extension.CreateFromDiscriminatorValue)?.AsList(); } },
                { "hasAttachments", n => { HasAttachments = n.GetBoolValue(); } },
                { "hideAttendees", n => { HideAttendees = n.GetBoolValue(); } },
                { "iCalUId", n => { ICalUId = n.GetStringValue(); } },
                { "importance", n => { Importance = n.GetEnumValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Importance>(); } },
                { "instances", n => { Instances = n.GetCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Event>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Event.CreateFromDiscriminatorValue)?.AsList(); } },
                { "isAllDay", n => { IsAllDay = n.GetBoolValue(); } },
                { "isCancelled", n => { IsCancelled = n.GetBoolValue(); } },
                { "isDraft", n => { IsDraft = n.GetBoolValue(); } },
                { "isOnlineMeeting", n => { IsOnlineMeeting = n.GetBoolValue(); } },
                { "isOrganizer", n => { IsOrganizer = n.GetBoolValue(); } },
                { "isReminderOn", n => { IsReminderOn = n.GetBoolValue(); } },
                { "location", n => { Location = n.GetObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Location>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Location.CreateFromDiscriminatorValue); } },
                { "locations", n => { Locations = n.GetCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Location>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Location.CreateFromDiscriminatorValue)?.AsList(); } },
                { "multiValueExtendedProperties", n => { MultiValueExtendedProperties = n.GetCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.MultiValueLegacyExtendedProperty>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.MultiValueLegacyExtendedProperty.CreateFromDiscriminatorValue)?.AsList(); } },
                { "onlineMeeting", n => { OnlineMeeting = n.GetObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.OnlineMeetingInfo>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.OnlineMeetingInfo.CreateFromDiscriminatorValue); } },
                { "onlineMeetingProvider", n => { OnlineMeetingProvider = n.GetEnumValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.OnlineMeetingProviderType>(); } },
                { "onlineMeetingUrl", n => { OnlineMeetingUrl = n.GetStringValue(); } },
                { "organizer", n => { Organizer = n.GetObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient.CreateFromDiscriminatorValue); } },
                { "originalEndTimeZone", n => { OriginalEndTimeZone = n.GetStringValue(); } },
                { "originalStart", n => { OriginalStart = n.GetDateTimeOffsetValue(); } },
                { "originalStartTimeZone", n => { OriginalStartTimeZone = n.GetStringValue(); } },
                { "recurrence", n => { Recurrence = n.GetObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.PatternedRecurrence>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.PatternedRecurrence.CreateFromDiscriminatorValue); } },
                { "reminderMinutesBeforeStart", n => { ReminderMinutesBeforeStart = n.GetIntValue(); } },
                { "responseRequested", n => { ResponseRequested = n.GetBoolValue(); } },
                { "responseStatus", n => { ResponseStatus = n.GetObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ResponseStatus>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ResponseStatus.CreateFromDiscriminatorValue); } },
                { "sensitivity", n => { Sensitivity = n.GetEnumValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Sensitivity>(); } },
                { "seriesMasterId", n => { SeriesMasterId = n.GetStringValue(); } },
                { "showAs", n => { ShowAs = n.GetEnumValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.FreeBusyStatus>(); } },
                { "singleValueExtendedProperties", n => { SingleValueExtendedProperties = n.GetCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.SingleValueLegacyExtendedProperty>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.SingleValueLegacyExtendedProperty.CreateFromDiscriminatorValue)?.AsList(); } },
                { "start", n => { Start = n.GetObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone.CreateFromDiscriminatorValue); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "transactionId", n => { TransactionId = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.EventType>(); } },
                { "webLink", n => { WebLink = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteBoolValue("allowNewTimeProposals", AllowNewTimeProposals);
            writer.WriteCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Attachment>("attachments", Attachments);
            writer.WriteCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Attendee>("attendees", Attendees);
            writer.WriteObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ItemBody>("body", Body);
            writer.WriteStringValue("bodyPreview", BodyPreview);
            writer.WriteObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Calendar>("calendar", Calendar);
            writer.WriteCollectionOfPrimitiveValues<string>("cancelledOccurrences", CancelledOccurrences);
            writer.WriteObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone>("end", End);
            writer.WriteCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Event>("exceptionOccurrences", ExceptionOccurrences);
            writer.WriteCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Extension>("extensions", Extensions);
            writer.WriteBoolValue("hasAttachments", HasAttachments);
            writer.WriteBoolValue("hideAttendees", HideAttendees);
            writer.WriteStringValue("iCalUId", ICalUId);
            writer.WriteEnumValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Importance>("importance", Importance);
            writer.WriteCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Event>("instances", Instances);
            writer.WriteBoolValue("isAllDay", IsAllDay);
            writer.WriteBoolValue("isCancelled", IsCancelled);
            writer.WriteBoolValue("isDraft", IsDraft);
            writer.WriteBoolValue("isOnlineMeeting", IsOnlineMeeting);
            writer.WriteBoolValue("isOrganizer", IsOrganizer);
            writer.WriteBoolValue("isReminderOn", IsReminderOn);
            writer.WriteObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Location>("location", Location);
            writer.WriteCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Location>("locations", Locations);
            writer.WriteCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.MultiValueLegacyExtendedProperty>("multiValueExtendedProperties", MultiValueExtendedProperties);
            writer.WriteObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.OnlineMeetingInfo>("onlineMeeting", OnlineMeeting);
            writer.WriteEnumValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.OnlineMeetingProviderType>("onlineMeetingProvider", OnlineMeetingProvider);
            writer.WriteStringValue("onlineMeetingUrl", OnlineMeetingUrl);
            writer.WriteObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>("organizer", Organizer);
            writer.WriteStringValue("originalEndTimeZone", OriginalEndTimeZone);
            writer.WriteDateTimeOffsetValue("originalStart", OriginalStart);
            writer.WriteStringValue("originalStartTimeZone", OriginalStartTimeZone);
            writer.WriteObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.PatternedRecurrence>("recurrence", Recurrence);
            writer.WriteIntValue("reminderMinutesBeforeStart", ReminderMinutesBeforeStart);
            writer.WriteBoolValue("responseRequested", ResponseRequested);
            writer.WriteObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ResponseStatus>("responseStatus", ResponseStatus);
            writer.WriteEnumValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Sensitivity>("sensitivity", Sensitivity);
            writer.WriteStringValue("seriesMasterId", SeriesMasterId);
            writer.WriteEnumValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.FreeBusyStatus>("showAs", ShowAs);
            writer.WriteCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.SingleValueLegacyExtendedProperty>("singleValueExtendedProperties", SingleValueExtendedProperties);
            writer.WriteObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone>("start", Start);
            writer.WriteStringValue("subject", Subject);
            writer.WriteStringValue("transactionId", TransactionId);
            writer.WriteEnumValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.EventType>("type", Type);
            writer.WriteStringValue("webLink", WebLink);
        }
    }
}
