// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    #pragma warning disable CS1591
    public enum FreeBusyStatus
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "free")]
        #pragma warning disable CS1591
        Free,
        #pragma warning restore CS1591
        [EnumMember(Value = "tentative")]
        #pragma warning disable CS1591
        Tentative,
        #pragma warning restore CS1591
        [EnumMember(Value = "busy")]
        #pragma warning disable CS1591
        Busy,
        #pragma warning restore CS1591
        [EnumMember(Value = "oof")]
        #pragma warning disable CS1591
        Oof,
        #pragma warning restore CS1591
        [EnumMember(Value = "workingElsewhere")]
        #pragma warning disable CS1591
        WorkingElsewhere,
        #pragma warning restore CS1591
    }
}
