// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    #pragma warning disable CS1591
    public enum LocationType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "default")]
        #pragma warning disable CS1591
        Default,
        #pragma warning restore CS1591
        [EnumMember(Value = "conferenceRoom")]
        #pragma warning disable CS1591
        ConferenceRoom,
        #pragma warning restore CS1591
        [EnumMember(Value = "homeAddress")]
        #pragma warning disable CS1591
        HomeAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "businessAddress")]
        #pragma warning disable CS1591
        BusinessAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "geoCoordinates")]
        #pragma warning disable CS1591
        GeoCoordinates,
        #pragma warning restore CS1591
        [EnumMember(Value = "streetAddress")]
        #pragma warning disable CS1591
        StreetAddress,
        #pragma warning restore CS1591
        [EnumMember(Value = "hotel")]
        #pragma warning disable CS1591
        Hotel,
        #pragma warning restore CS1591
        [EnumMember(Value = "restaurant")]
        #pragma warning disable CS1591
        Restaurant,
        #pragma warning restore CS1591
        [EnumMember(Value = "localBusiness")]
        #pragma warning disable CS1591
        LocalBusiness,
        #pragma warning restore CS1591
        [EnumMember(Value = "postalAddress")]
        #pragma warning disable CS1591
        PostalAddress,
        #pragma warning restore CS1591
    }
}
