// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    #pragma warning disable CS1591
    public enum LocationUniqueIdType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "unknown")]
        #pragma warning disable CS1591
        Unknown,
        #pragma warning restore CS1591
        [EnumMember(Value = "locationStore")]
        #pragma warning disable CS1591
        LocationStore,
        #pragma warning restore CS1591
        [EnumMember(Value = "directory")]
        #pragma warning disable CS1591
        Directory,
        #pragma warning restore CS1591
        [EnumMember(Value = "private")]
        #pragma warning disable CS1591
        Private,
        #pragma warning restore CS1591
        [EnumMember(Value = "bing")]
        #pragma warning disable CS1591
        Bing,
        #pragma warning restore CS1591
    }
}
