// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    #pragma warning disable CS1591
    public enum MeetingMessageType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "meetingRequest")]
        #pragma warning disable CS1591
        MeetingRequest,
        #pragma warning restore CS1591
        [EnumMember(Value = "meetingCancelled")]
        #pragma warning disable CS1591
        MeetingCancelled,
        #pragma warning restore CS1591
        [EnumMember(Value = "meetingAccepted")]
        #pragma warning disable CS1591
        MeetingAccepted,
        #pragma warning restore CS1591
        [EnumMember(Value = "meetingTenativelyAccepted")]
        #pragma warning disable CS1591
        MeetingTenativelyAccepted,
        #pragma warning restore CS1591
        [EnumMember(Value = "meetingDeclined")]
        #pragma warning disable CS1591
        MeetingDeclined,
        #pragma warning restore CS1591
    }
}
