// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    #pragma warning disable CS1591
    public enum MeetingRequestType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "none")]
        #pragma warning disable CS1591
        None,
        #pragma warning restore CS1591
        [EnumMember(Value = "newMeetingRequest")]
        #pragma warning disable CS1591
        NewMeetingRequest,
        #pragma warning restore CS1591
        [EnumMember(Value = "fullUpdate")]
        #pragma warning disable CS1591
        FullUpdate,
        #pragma warning restore CS1591
        [EnumMember(Value = "informationalUpdate")]
        #pragma warning disable CS1591
        InformationalUpdate,
        #pragma warning restore CS1591
        [EnumMember(Value = "silentUpdate")]
        #pragma warning disable CS1591
        SilentUpdate,
        #pragma warning restore CS1591
        [EnumMember(Value = "outdated")]
        #pragma warning disable CS1591
        Outdated,
        #pragma warning restore CS1591
        [EnumMember(Value = "principalWantsCopy")]
        #pragma warning disable CS1591
        PrincipalWantsCopy,
        #pragma warning restore CS1591
    }
}
