// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    #pragma warning disable CS1591
    public partial class Message : global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.OutlookItem, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The fileAttachment and itemAttachment attachments for the message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Attachment>? Attachments
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Attachment>?>("attachments"); }
            set { BackingStore?.Set("attachments", value); }
        }
#nullable restore
#else
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Attachment> Attachments
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Attachment>>("attachments"); }
            set { BackingStore?.Set("attachments", value); }
        }
#endif
        /// <summary>The Bcc: recipients for the message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>? BccRecipients
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>?>("bccRecipients"); }
            set { BackingStore?.Set("bccRecipients", value); }
        }
#nullable restore
#else
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient> BccRecipients
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>>("bccRecipients"); }
            set { BackingStore?.Set("bccRecipients", value); }
        }
#endif
        /// <summary>The body of the message. It can be in HTML or text format. Find out about safe HTML in a message body.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ItemBody? Body
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ItemBody?>("body"); }
            set { BackingStore?.Set("body", value); }
        }
#nullable restore
#else
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ItemBody Body
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ItemBody>("body"); }
            set { BackingStore?.Set("body", value); }
        }
#endif
        /// <summary>The first 255 characters of the message body. It is in text format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BodyPreview
        {
            get { return BackingStore?.Get<string?>("bodyPreview"); }
            set { BackingStore?.Set("bodyPreview", value); }
        }
#nullable restore
#else
        public string BodyPreview
        {
            get { return BackingStore?.Get<string>("bodyPreview"); }
            set { BackingStore?.Set("bodyPreview", value); }
        }
#endif
        /// <summary>The Cc: recipients for the message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>? CcRecipients
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>?>("ccRecipients"); }
            set { BackingStore?.Set("ccRecipients", value); }
        }
#nullable restore
#else
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient> CcRecipients
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>>("ccRecipients"); }
            set { BackingStore?.Set("ccRecipients", value); }
        }
#endif
        /// <summary>The ID of the conversation the email belongs to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConversationId
        {
            get { return BackingStore?.Get<string?>("conversationId"); }
            set { BackingStore?.Set("conversationId", value); }
        }
#nullable restore
#else
        public string ConversationId
        {
            get { return BackingStore?.Get<string>("conversationId"); }
            set { BackingStore?.Set("conversationId", value); }
        }
#endif
        /// <summary>Indicates the position of the message within the conversation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public byte[]? ConversationIndex
        {
            get { return BackingStore?.Get<byte[]?>("conversationIndex"); }
            set { BackingStore?.Set("conversationIndex", value); }
        }
#nullable restore
#else
        public byte[] ConversationIndex
        {
            get { return BackingStore?.Get<byte[]>("conversationIndex"); }
            set { BackingStore?.Set("conversationIndex", value); }
        }
#endif
        /// <summary>The collection of open extensions defined for the message. Nullable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Extension>? Extensions
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Extension>?>("extensions"); }
            set { BackingStore?.Set("extensions", value); }
        }
#nullable restore
#else
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Extension> Extensions
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Extension>>("extensions"); }
            set { BackingStore?.Set("extensions", value); }
        }
#endif
        /// <summary>Indicates the status, start date, due date, or completion date for the message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.FollowupFlag? Flag
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.FollowupFlag?>("flag"); }
            set { BackingStore?.Set("flag", value); }
        }
#nullable restore
#else
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.FollowupFlag Flag
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.FollowupFlag>("flag"); }
            set { BackingStore?.Set("flag", value); }
        }
#endif
        /// <summary>The owner of the mailbox from which the message is sent. In most cases, this value is the same as the sender property, except for sharing or delegation scenarios. The value must correspond to the actual mailbox used. Find out more about setting the from and sender properties of a message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient? From
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient?>("from"); }
            set { BackingStore?.Set("from", value); }
        }
#nullable restore
#else
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient From
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>("from"); }
            set { BackingStore?.Set("from", value); }
        }
#endif
        /// <summary>Indicates whether the message has attachments. This property doesn&apos;t include inline attachments, so if a message contains only inline attachments, this property is false. To verify the existence of inline attachments, parse the body property to look for a src attribute, such as &lt;IMG src=&apos;cid:image001.jpg@01D26CD8.6C05F070&apos;&gt;.</summary>
        public bool? HasAttachments
        {
            get { return BackingStore?.Get<bool?>("hasAttachments"); }
            set { BackingStore?.Set("hasAttachments", value); }
        }
        /// <summary>The importance of the message. The possible values are: low, normal, and high.</summary>
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Importance? Importance
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Importance?>("importance"); }
            set { BackingStore?.Set("importance", value); }
        }
        /// <summary>The classification of the message for the user, based on inferred relevance or importance, or on an explicit override. The possible values are: focused or other.</summary>
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.InferenceClassificationType? InferenceClassification
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.InferenceClassificationType?>("inferenceClassification"); }
            set { BackingStore?.Set("inferenceClassification", value); }
        }
        /// <summary>A collection of message headers defined by RFC5322. The set includes message headers indicating the network path taken by a message from the sender to the recipient. It can also contain custom message headers that hold app data for the message.  Requires $select to retrieve. Read-only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.InternetMessageHeader>? InternetMessageHeaders
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.InternetMessageHeader>?>("internetMessageHeaders"); }
            set { BackingStore?.Set("internetMessageHeaders", value); }
        }
#nullable restore
#else
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.InternetMessageHeader> InternetMessageHeaders
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.InternetMessageHeader>>("internetMessageHeaders"); }
            set { BackingStore?.Set("internetMessageHeaders", value); }
        }
#endif
        /// <summary>The message ID in the format specified by RFC2822.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InternetMessageId
        {
            get { return BackingStore?.Get<string?>("internetMessageId"); }
            set { BackingStore?.Set("internetMessageId", value); }
        }
#nullable restore
#else
        public string InternetMessageId
        {
            get { return BackingStore?.Get<string>("internetMessageId"); }
            set { BackingStore?.Set("internetMessageId", value); }
        }
#endif
        /// <summary>Indicates whether a read receipt is requested for the message.</summary>
        public bool? IsDeliveryReceiptRequested
        {
            get { return BackingStore?.Get<bool?>("isDeliveryReceiptRequested"); }
            set { BackingStore?.Set("isDeliveryReceiptRequested", value); }
        }
        /// <summary>Indicates whether the message is a draft. A message is a draft if it hasn&apos;t been sent yet.</summary>
        public bool? IsDraft
        {
            get { return BackingStore?.Get<bool?>("isDraft"); }
            set { BackingStore?.Set("isDraft", value); }
        }
        /// <summary>Indicates whether the message has been read.</summary>
        public bool? IsRead
        {
            get { return BackingStore?.Get<bool?>("isRead"); }
            set { BackingStore?.Set("isRead", value); }
        }
        /// <summary>Indicates whether a read receipt is requested for the message.</summary>
        public bool? IsReadReceiptRequested
        {
            get { return BackingStore?.Get<bool?>("isReadReceiptRequested"); }
            set { BackingStore?.Set("isReadReceiptRequested", value); }
        }
        /// <summary>The collection of multi-value extended properties defined for the message. Nullable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.MultiValueLegacyExtendedProperty>? MultiValueExtendedProperties
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.MultiValueLegacyExtendedProperty>?>("multiValueExtendedProperties"); }
            set { BackingStore?.Set("multiValueExtendedProperties", value); }
        }
#nullable restore
#else
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.MultiValueLegacyExtendedProperty> MultiValueExtendedProperties
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.MultiValueLegacyExtendedProperty>>("multiValueExtendedProperties"); }
            set { BackingStore?.Set("multiValueExtendedProperties", value); }
        }
#endif
        /// <summary>The unique identifier for the message&apos;s parent mailFolder.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentFolderId
        {
            get { return BackingStore?.Get<string?>("parentFolderId"); }
            set { BackingStore?.Set("parentFolderId", value); }
        }
#nullable restore
#else
        public string ParentFolderId
        {
            get { return BackingStore?.Get<string>("parentFolderId"); }
            set { BackingStore?.Set("parentFolderId", value); }
        }
#endif
        /// <summary>The date and time the message was received.  The date and time information uses ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z.</summary>
        public DateTimeOffset? ReceivedDateTime
        {
            get { return BackingStore?.Get<DateTimeOffset?>("receivedDateTime"); }
            set { BackingStore?.Set("receivedDateTime", value); }
        }
        /// <summary>The email addresses to use when replying.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>? ReplyTo
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>?>("replyTo"); }
            set { BackingStore?.Set("replyTo", value); }
        }
#nullable restore
#else
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient> ReplyTo
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>>("replyTo"); }
            set { BackingStore?.Set("replyTo", value); }
        }
#endif
        /// <summary>The account that is used to generate the message. In most cases, this value is the same as the from property. You can set this property to a different value when sending a message from a shared mailbox, for a shared calendar, or as a delegate. In any case, the value must correspond to the actual mailbox used. Find out more about setting the from and sender properties of a message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient? Sender
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient?>("sender"); }
            set { BackingStore?.Set("sender", value); }
        }
#nullable restore
#else
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient Sender
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>("sender"); }
            set { BackingStore?.Set("sender", value); }
        }
#endif
        /// <summary>The date and time the message was sent.  The date and time information uses ISO 8601 format and is always in UTC time. For example, midnight UTC on Jan 1, 2014 is 2014-01-01T00:00:00Z.</summary>
        public DateTimeOffset? SentDateTime
        {
            get { return BackingStore?.Get<DateTimeOffset?>("sentDateTime"); }
            set { BackingStore?.Set("sentDateTime", value); }
        }
        /// <summary>The collection of single-value extended properties defined for the message. Nullable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.SingleValueLegacyExtendedProperty>? SingleValueExtendedProperties
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.SingleValueLegacyExtendedProperty>?>("singleValueExtendedProperties"); }
            set { BackingStore?.Set("singleValueExtendedProperties", value); }
        }
#nullable restore
#else
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.SingleValueLegacyExtendedProperty> SingleValueExtendedProperties
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.SingleValueLegacyExtendedProperty>>("singleValueExtendedProperties"); }
            set { BackingStore?.Set("singleValueExtendedProperties", value); }
        }
#endif
        /// <summary>The subject of the message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject
        {
            get { return BackingStore?.Get<string?>("subject"); }
            set { BackingStore?.Set("subject", value); }
        }
#nullable restore
#else
        public string Subject
        {
            get { return BackingStore?.Get<string>("subject"); }
            set { BackingStore?.Set("subject", value); }
        }
#endif
        /// <summary>The To: recipients for the message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>? ToRecipients
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>?>("toRecipients"); }
            set { BackingStore?.Set("toRecipients", value); }
        }
#nullable restore
#else
        public List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient> ToRecipients
        {
            get { return BackingStore?.Get<List<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>>("toRecipients"); }
            set { BackingStore?.Set("toRecipients", value); }
        }
#endif
        /// <summary>The part of the body of the message that is unique to the current message. uniqueBody is not returned by default but can be retrieved for a given message by use of the ?$select=uniqueBody query. It can be in HTML or text format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ItemBody? UniqueBody
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ItemBody?>("uniqueBody"); }
            set { BackingStore?.Set("uniqueBody", value); }
        }
#nullable restore
#else
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ItemBody UniqueBody
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ItemBody>("uniqueBody"); }
            set { BackingStore?.Set("uniqueBody", value); }
        }
#endif
        /// <summary>The URL to open the message in Outlook on the web.You can append an ispopout argument to the end of the URL to change how the message is displayed. If ispopout is not present or if it is set to 1, then the message is shown in a popout window. If ispopout is set to 0, the browser shows the message in the Outlook on the web review pane.The message opens in the browser if you are signed in to your mailbox via Outlook on the web. You are prompted to sign in if you are not already signed in with the browser.This URL cannot be accessed from within an iFrame.NOTE: When using this URL to access a message from a mailbox with delegate permissions, both the signed-in user and the target mailbox must be in the same database region. For example, an error is returned when a user with a mailbox in the EUR (Europe) region attempts to access messages from a mailbox in the NAM (North America) region.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WebLink
        {
            get { return BackingStore?.Get<string?>("webLink"); }
            set { BackingStore?.Set("webLink", value); }
        }
#nullable restore
#else
        public string WebLink
        {
            get { return BackingStore?.Get<string>("webLink"); }
            set { BackingStore?.Set("webLink", value); }
        }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Message"/> and sets the default values.
        /// </summary>
        public Message() : base()
        {
            OdataType = "#microsoft.graph.message";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Message"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Message CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("@odata.type")?.GetStringValue();
            return mappingValue switch
            {
                "#microsoft.graph.calendarSharingMessage" => new global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.CalendarSharingMessage(),
                "#microsoft.graph.eventMessage" => new global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.EventMessage(),
                "#microsoft.graph.eventMessageRequest" => new global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.EventMessageRequest(),
                "#microsoft.graph.eventMessageResponse" => new global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.EventMessageResponse(),
                _ => new global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Message(),
            };
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "attachments", n => { Attachments = n.GetCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Attachment>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Attachment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "bccRecipients", n => { BccRecipients = n.GetCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient.CreateFromDiscriminatorValue)?.AsList(); } },
                { "body", n => { Body = n.GetObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ItemBody>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ItemBody.CreateFromDiscriminatorValue); } },
                { "bodyPreview", n => { BodyPreview = n.GetStringValue(); } },
                { "ccRecipients", n => { CcRecipients = n.GetCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient.CreateFromDiscriminatorValue)?.AsList(); } },
                { "conversationId", n => { ConversationId = n.GetStringValue(); } },
                { "conversationIndex", n => { ConversationIndex = n.GetByteArrayValue(); } },
                { "extensions", n => { Extensions = n.GetCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Extension>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Extension.CreateFromDiscriminatorValue)?.AsList(); } },
                { "flag", n => { Flag = n.GetObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.FollowupFlag>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.FollowupFlag.CreateFromDiscriminatorValue); } },
                { "from", n => { From = n.GetObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient.CreateFromDiscriminatorValue); } },
                { "hasAttachments", n => { HasAttachments = n.GetBoolValue(); } },
                { "importance", n => { Importance = n.GetEnumValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Importance>(); } },
                { "inferenceClassification", n => { InferenceClassification = n.GetEnumValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.InferenceClassificationType>(); } },
                { "internetMessageHeaders", n => { InternetMessageHeaders = n.GetCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.InternetMessageHeader>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.InternetMessageHeader.CreateFromDiscriminatorValue)?.AsList(); } },
                { "internetMessageId", n => { InternetMessageId = n.GetStringValue(); } },
                { "isDeliveryReceiptRequested", n => { IsDeliveryReceiptRequested = n.GetBoolValue(); } },
                { "isDraft", n => { IsDraft = n.GetBoolValue(); } },
                { "isRead", n => { IsRead = n.GetBoolValue(); } },
                { "isReadReceiptRequested", n => { IsReadReceiptRequested = n.GetBoolValue(); } },
                { "multiValueExtendedProperties", n => { MultiValueExtendedProperties = n.GetCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.MultiValueLegacyExtendedProperty>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.MultiValueLegacyExtendedProperty.CreateFromDiscriminatorValue)?.AsList(); } },
                { "parentFolderId", n => { ParentFolderId = n.GetStringValue(); } },
                { "receivedDateTime", n => { ReceivedDateTime = n.GetDateTimeOffsetValue(); } },
                { "replyTo", n => { ReplyTo = n.GetCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient.CreateFromDiscriminatorValue)?.AsList(); } },
                { "sender", n => { Sender = n.GetObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient.CreateFromDiscriminatorValue); } },
                { "sentDateTime", n => { SentDateTime = n.GetDateTimeOffsetValue(); } },
                { "singleValueExtendedProperties", n => { SingleValueExtendedProperties = n.GetCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.SingleValueLegacyExtendedProperty>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.SingleValueLegacyExtendedProperty.CreateFromDiscriminatorValue)?.AsList(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "toRecipients", n => { ToRecipients = n.GetCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient.CreateFromDiscriminatorValue)?.AsList(); } },
                { "uniqueBody", n => { UniqueBody = n.GetObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ItemBody>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ItemBody.CreateFromDiscriminatorValue); } },
                { "webLink", n => { WebLink = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public override void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            base.Serialize(writer);
            writer.WriteCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Attachment>("attachments", Attachments);
            writer.WriteCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>("bccRecipients", BccRecipients);
            writer.WriteObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ItemBody>("body", Body);
            writer.WriteStringValue("bodyPreview", BodyPreview);
            writer.WriteCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>("ccRecipients", CcRecipients);
            writer.WriteStringValue("conversationId", ConversationId);
            writer.WriteByteArrayValue("conversationIndex", ConversationIndex);
            writer.WriteCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Extension>("extensions", Extensions);
            writer.WriteObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.FollowupFlag>("flag", Flag);
            writer.WriteObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>("from", From);
            writer.WriteBoolValue("hasAttachments", HasAttachments);
            writer.WriteEnumValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Importance>("importance", Importance);
            writer.WriteEnumValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.InferenceClassificationType>("inferenceClassification", InferenceClassification);
            writer.WriteCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.InternetMessageHeader>("internetMessageHeaders", InternetMessageHeaders);
            writer.WriteStringValue("internetMessageId", InternetMessageId);
            writer.WriteBoolValue("isDeliveryReceiptRequested", IsDeliveryReceiptRequested);
            writer.WriteBoolValue("isDraft", IsDraft);
            writer.WriteBoolValue("isRead", IsRead);
            writer.WriteBoolValue("isReadReceiptRequested", IsReadReceiptRequested);
            writer.WriteCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.MultiValueLegacyExtendedProperty>("multiValueExtendedProperties", MultiValueExtendedProperties);
            writer.WriteStringValue("parentFolderId", ParentFolderId);
            writer.WriteDateTimeOffsetValue("receivedDateTime", ReceivedDateTime);
            writer.WriteCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>("replyTo", ReplyTo);
            writer.WriteObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>("sender", Sender);
            writer.WriteDateTimeOffsetValue("sentDateTime", SentDateTime);
            writer.WriteCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.SingleValueLegacyExtendedProperty>("singleValueExtendedProperties", SingleValueExtendedProperties);
            writer.WriteStringValue("subject", Subject);
            writer.WriteCollectionOfObjectValues<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.Recipient>("toRecipients", ToRecipients);
            writer.WriteObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.ItemBody>("uniqueBody", UniqueBody);
            writer.WriteStringValue("webLink", WebLink);
        }
    }
}
