// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions.Store;
using System.Collections.Generic;
using System.IO;
using System;
namespace OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    #pragma warning disable CS1591
    public partial class PatternedRecurrence : IAdditionalDataHolder, IBackedModel, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData
        {
            get { return BackingStore.Get<IDictionary<string, object>>("AdditionalData") ?? new Dictionary<string, object>(); }
            set { BackingStore.Set("AdditionalData", value); }
        }
        /// <summary>Stores model information.</summary>
        public IBackingStore BackingStore { get; private set; }
        /// <summary>The OdataType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OdataType
        {
            get { return BackingStore?.Get<string?>("@odata.type"); }
            set { BackingStore?.Set("@odata.type", value); }
        }
#nullable restore
#else
        public string OdataType
        {
            get { return BackingStore?.Get<string>("@odata.type"); }
            set { BackingStore?.Set("@odata.type", value); }
        }
#endif
        /// <summary>The frequency of an event.  For access reviews: Do not specify this property for a one-time access review.  Only interval, dayOfMonth, and type (weekly, absoluteMonthly) properties of recurrencePattern are supported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.RecurrencePattern? Pattern
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.RecurrencePattern?>("pattern"); }
            set { BackingStore?.Set("pattern", value); }
        }
#nullable restore
#else
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.RecurrencePattern Pattern
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.RecurrencePattern>("pattern"); }
            set { BackingStore?.Set("pattern", value); }
        }
#endif
        /// <summary>The duration of an event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.RecurrenceRange? Range
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.RecurrenceRange?>("range"); }
            set { BackingStore?.Set("range", value); }
        }
#nullable restore
#else
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.RecurrenceRange Range
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.RecurrenceRange>("range"); }
            set { BackingStore?.Set("range", value); }
        }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.PatternedRecurrence"/> and sets the default values.
        /// </summary>
        public PatternedRecurrence()
        {
            BackingStore = BackingStoreFactorySingleton.Instance.CreateBackingStore();
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.PatternedRecurrence"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.PatternedRecurrence CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.PatternedRecurrence();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "@odata.type", n => { OdataType = n.GetStringValue(); } },
                { "pattern", n => { Pattern = n.GetObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.RecurrencePattern>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.RecurrencePattern.CreateFromDiscriminatorValue); } },
                { "range", n => { Range = n.GetObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.RecurrenceRange>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.RecurrenceRange.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("@odata.type", OdataType);
            writer.WriteObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.RecurrencePattern>("pattern", Pattern);
            writer.WriteObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.RecurrenceRange>("range", Range);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
