// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    #pragma warning disable CS1591
    public enum PhoneType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "home")]
        #pragma warning disable CS1591
        Home,
        #pragma warning restore CS1591
        [EnumMember(Value = "business")]
        #pragma warning disable CS1591
        Business,
        #pragma warning restore CS1591
        [EnumMember(Value = "mobile")]
        #pragma warning disable CS1591
        Mobile,
        #pragma warning restore CS1591
        [EnumMember(Value = "other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
        [EnumMember(Value = "assistant")]
        #pragma warning disable CS1591
        Assistant,
        #pragma warning restore CS1591
        [EnumMember(Value = "homeFax")]
        #pragma warning disable CS1591
        HomeFax,
        #pragma warning restore CS1591
        [EnumMember(Value = "businessFax")]
        #pragma warning disable CS1591
        BusinessFax,
        #pragma warning restore CS1591
        [EnumMember(Value = "otherFax")]
        #pragma warning disable CS1591
        OtherFax,
        #pragma warning restore CS1591
        [EnumMember(Value = "pager")]
        #pragma warning disable CS1591
        Pager,
        #pragma warning restore CS1591
        [EnumMember(Value = "radio")]
        #pragma warning disable CS1591
        Radio,
        #pragma warning restore CS1591
    }
}
