// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    #pragma warning disable CS1591
    public enum RecurrencePatternType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "daily")]
        #pragma warning disable CS1591
        Daily,
        #pragma warning restore CS1591
        [EnumMember(Value = "weekly")]
        #pragma warning disable CS1591
        Weekly,
        #pragma warning restore CS1591
        [EnumMember(Value = "absoluteMonthly")]
        #pragma warning disable CS1591
        AbsoluteMonthly,
        #pragma warning restore CS1591
        [EnumMember(Value = "relativeMonthly")]
        #pragma warning disable CS1591
        RelativeMonthly,
        #pragma warning restore CS1591
        [EnumMember(Value = "absoluteYearly")]
        #pragma warning disable CS1591
        AbsoluteYearly,
        #pragma warning restore CS1591
        [EnumMember(Value = "relativeYearly")]
        #pragma warning disable CS1591
        RelativeYearly,
        #pragma warning restore CS1591
    }
}
