// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    #pragma warning disable CS1591
    public enum ReferenceNumeric
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "-INF")]
        #pragma warning disable CS1591
        Minus_INF,
        #pragma warning restore CS1591
        [EnumMember(Value = "INF")]
        #pragma warning disable CS1591
        INF,
        #pragma warning restore CS1591
        [EnumMember(Value = "NaN")]
        #pragma warning disable CS1591
        NaN,
        #pragma warning restore CS1591
    }
}
