// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions.Store;
using OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models;
using System.Collections.Generic;
using System.IO;
using System;
namespace OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.Calendars.Item.GetSchedule
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    #pragma warning disable CS1591
    public partial class GetSchedulePostRequestBody : IAdditionalDataHolder, IBackedModel, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData
        {
            get { return BackingStore.Get<IDictionary<string, object>>("AdditionalData") ?? new Dictionary<string, object>(); }
            set { BackingStore.Set("AdditionalData", value); }
        }
        /// <summary>The AvailabilityViewInterval property</summary>
        public int? AvailabilityViewInterval
        {
            get { return BackingStore?.Get<int?>("AvailabilityViewInterval"); }
            set { BackingStore?.Set("AvailabilityViewInterval", value); }
        }
        /// <summary>Stores model information.</summary>
        public IBackingStore BackingStore { get; private set; }
        /// <summary>The EndTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone? EndTime
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone?>("EndTime"); }
            set { BackingStore?.Set("EndTime", value); }
        }
#nullable restore
#else
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone EndTime
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone>("EndTime"); }
            set { BackingStore?.Set("EndTime", value); }
        }
#endif
        /// <summary>The Schedules property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Schedules
        {
            get { return BackingStore?.Get<List<string>?>("Schedules"); }
            set { BackingStore?.Set("Schedules", value); }
        }
#nullable restore
#else
        public List<string> Schedules
        {
            get { return BackingStore?.Get<List<string>>("Schedules"); }
            set { BackingStore?.Set("Schedules", value); }
        }
#endif
        /// <summary>The StartTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone? StartTime
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone?>("StartTime"); }
            set { BackingStore?.Set("StartTime", value); }
        }
#nullable restore
#else
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone StartTime
        {
            get { return BackingStore?.Get<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone>("StartTime"); }
            set { BackingStore?.Set("StartTime", value); }
        }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.Calendars.Item.GetSchedule.GetSchedulePostRequestBody"/> and sets the default values.
        /// </summary>
        public GetSchedulePostRequestBody()
        {
            BackingStore = BackingStoreFactorySingleton.Instance.CreateBackingStore();
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.Calendars.Item.GetSchedule.GetSchedulePostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.Calendars.Item.GetSchedule.GetSchedulePostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.Calendars.Item.GetSchedule.GetSchedulePostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AvailabilityViewInterval", n => { AvailabilityViewInterval = n.GetIntValue(); } },
                { "EndTime", n => { EndTime = n.GetObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone.CreateFromDiscriminatorValue); } },
                { "Schedules", n => { Schedules = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "StartTime", n => { StartTime = n.GetObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone>(global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("AvailabilityViewInterval", AvailabilityViewInterval);
            writer.WriteObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone>("EndTime", EndTime);
            writer.WriteCollectionOfPrimitiveValues<string>("Schedules", Schedules);
            writer.WriteObjectValue<global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Models.DateTimeTimeZone>("StartTime", StartTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
