// <auto-generated/>
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.Calendars;
using OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.Events;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me
{
    /// <summary>
    /// Builds and executes requests for operations under \me
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.17.0")]
    public partial class MeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Provides operations to manage the calendars property of the microsoft.graph.user entity.</summary>
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.Calendars.CalendarsRequestBuilder Calendars
        {
            get => new global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.Calendars.CalendarsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Provides operations to manage the events property of the microsoft.graph.user entity.</summary>
        public global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.Events.EventsRequestBuilder Events
        {
            get => new global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.Events.EventsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.MeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/me", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::OutlookGoogleCalendarSync.Outlook.Graph.CustomClient.Me.MeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/me", rawUrl)
        {
        }
    }
}
